variables:
  download_url: "https://common-lisp.net/project/cmucl/downloads/snapshots/2019/06"
  version: "2019-06-x86"
  bootstrap: ""

linux-runner:
  tags:
    - linux
  before_script:
    - wget -nv $download_url/cmucl-$version-linux.tar.bz2
    - wget -nv $download_url/cmucl-$version-linux.extra.tar.bz2
    - mkdir snapshot
    - (cd snapshot; tar xjf ../cmucl-$version-linux.tar.bz2; tar xjf ../cmucl-$version-linux.extra.tar.bz2)
  script:
    - bin/build.sh $bootstrap -C "" -o snapshot/bin/lisp
    - bin/make-dist.sh -I dist linux-4
    - bin/run-tests.sh -l dist/bin/lisp 2>&1 | tee test.log

osx-runner:
  tags:
    - osx
  before_script:
    - curl -s -o cmucl-$version-darwin.tar.bz2 $download_url/cmucl-$version-darwin.tar.bz2
    - mkdir snapshot
    - (cd snapshot; tar xjf ../cmucl-$version-darwin.tar.bz2)
  script:
    - bin/build.sh $bootstrap -C "" -o snapshot/bin/lisp
    - bin/make-dist.sh -I dist darwin-4
    - bin/run-tests.sh -l dist/bin/lisp 2>&1 | tee test.log
