.build_cmucl:
  script:
    # Do cross compile first
    #- bin/create-target.sh xtarget x86_linux_clang
    #- bin/create-target.sh xcross x86_linux_clang
    #- bin/cross-build-world.sh -crl -B boot-2020-04-1 xtarget xcross src/tools/cross-scripts/cross-x86-x86.lisp snapshot/bin/lisp
    # Regular build using the cross-compiled result or snapshot.  The
    # analyzer job requires gcc, so make sure we build with gcc here
    # instead of clang. 
    - bin/build.sh $bootstrap -b build -R -C "" -o snapshot/bin/lisp
    # When the result of `git describe` cannot be used as a version
    # string, an alternative can be provided with the -V flag
    - bin/make-dist.sh -I dist build-4
    
